[package]
name = "backend"
version = "0.5.5"
edition = "2021"

[dependencies]
confy = { version = "0.5", features = ["ron_conf"], default-features = false }
crossbeam-channel = "0.5"
derivative = "2.2"
ffmpeg-sidecar = "0.3"
ffprobe = { git = "https://github.com/avsaase/ffprobe-rs/", branch = "suppress-console-windows" }
hex = "0.4"
image = "0.25"
lazy_static = "1.5"
imageproc = "0.25"
parse-display = "0.10"
rayon = "1"
regex = "1"
ab_glyph = "0.2"
serde = { version = "1", features = ["derive"] }
srtparse = "0.2"
thiserror = "2"
tracing = "0.1"
bytemuck = "1"

[dev-dependencies]
claims = "0.8"
